/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 astro.gltf --transform
Author: Rude Randal (https://sketchfab.com/Rude_Randal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-astronaut-5bb793a440164595ac4cb605822b2d88
Title: Little Astronaut
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/astro-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Character_Texture}
        position={[0, 0.869, -0.072]}
        // scale={0.531}
      />
    </group>
  );
}

useGLTF.preload("/astro-transformed.glb");
